version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d/:ro
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    restart: always
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db


volumes:
  mysql-data:
