"""empty message

Revision ID: 7062066a47c2
Revises: 7a7f5c702bc0
Create Date: 2021-06-27 03:06:08.517388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7062066a47c2'
down_revision = '7a7f5c702bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_delete')
    # ### end Alembic commands ###
