"""empty message

Revision ID: 7a7f5c702bc0
Revises: 85c3da0353e6
Create Date: 2021-04-08 09:18:10.595962

"""
from alembic import op
from sqlalchemy import func
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7f5c702bc0'
down_revision = '85c3da0353e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('old_price', sa.BigInteger(), nullable=True),
    sa.Column('new_price', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(),server_default=func.current_timestamp(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(),server_default=func.current_timestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
