"""empty message

Revision ID: 99f3f339f2be
Revises: 
Create Date: 2020-05-06 06:21:32.703626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '99f3f339f2be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('storage_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=func.current_timestamp(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=func.current_timestamp(),
              server_onupdate=func.current_timestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=func.current_timestamp(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=func.current_timestamp(),
              server_onupdate=func.current_timestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('anonymous_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=func.current_timestamp(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(),server_default=func.current_timestamp(),
              server_onupdate=func.current_timestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('files')
    # ### end Alembic commands ###
